FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# goCamping

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/gocamping/campsites]

### List All Campsites [GET]

+ Response 200 (application/json)

        [
            {
                "campsite": [
                    {
                    "adultPrice": "17.0",
                    "babyPrice": "0.0",
                    "campingCardDiscount": "7.0",
                    "childPrice": "8.0",
                    "contact": "23173243",
                    "description": "
                Local tranquilo e ideal para umas férias e contacto com a Natureza. Locais atrativos e naturais perto do parque.
                 Wi-Fi gratuito
                ",
                    "id": "20058",
                    "location": "São Jorge, Açores",
                    "title": "Parque de Campismo da Fajã do Ouvidor"
                        }
                    ]
                }
            }
        ]